#pragma once

#define TABLE_LEFT_UP_CORNER (char)218
#define TABLE_RIGHT_UP_CORNER (char)191
#define TABLE_LEFT_DOWN_CORNER (char)192
#define TABLE_RIGHT_DOWN_CORNER (char)217

#define TABLE_HORIZONTAL_LINE (char)196
#define TABLE_VERTICAL_LINE (char)179
#define TABLE_HORIZONTAL_DOUBLE_LINE (char)205

#define TABLE_LEFT_DOUBLE_CORNER (char)198
#define TABLE_RIGHT_DOUBLE_CORNER (char)181

#define TABLE_CROSS (char)197
#define TABLE_CROSS_DOUBLE (char)216
#define TABLE_T (char)194
#define TABLE_T_FLIPPED (char)193
#define TABLE_T_DOUBLE (char)209